import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {LayoutDashboard,Users,WalletCards,Package as PackageIcon,LogOut,Copy,ArrowUpRight,Menu,X,ShieldCheck,RefreshCw,History,CheckCircle2,MessageCircle,BookOpen,ExternalLink,UsersRound,ReceiptText,HandCoins,Settings2,Search,LockKeyhole,LogIn,Ban,UserCheck,Clock3,Check,ChevronDown,BarChart3} from "lucide-react";
import "./styles.css";
const API=(import.meta.env.VITE_API_URL||"https://nexora-api-shxf.onrender.com/api").replace(/\/$/,"");
const money=n=>`KSh ${Number(n||0).toLocaleString()}`;
const PHONE_RE=/^(?:07\d{8}|011\d{7}|2547\d{8}|2541\d{8})$/;
const cleanPhone=v=>String(v||"").trim().replace(/[\s().-]/g,"").replace(/^\+/,"");
const validPhone=v=>PHONE_RE.test(cleanPhone(v));
async function api(path,opts={}){const token=localStorage.getItem("token");const r=await fetch(API+path,{...opts,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Request failed");return d}
function Instructions({onClose}){return <div className="modalbackdrop" onClick={onClose}><div className="modal instructions" onClick={e=>e.stopPropagation()}><div className="modalhead"><div><span className="pill">NEXORA GUIDE</span><h2>How to use NEXORA</h2></div><button className="iconbtn" onClick={onClose}><X size={20}/></button></div><div className="instructionbody"><div><b>1. Create an account</b><p>Register with your full name, email, password and a valid Kenyan M-Pesa phone number. Accepted formats are 07…, 011…, 2547… and 2541….</p></div><div><b>2. Choose a package</b><p>Open <strong>Packages</strong>, review the package price and referral commissions, then select <strong>Purchase package</strong>.</p></div><div><b>3. Complete payment</b><p>Enter the M-Pesa number that should receive the payment prompt and approve the request on your phone.</p></div><div><b>4. Check your package</b><p>After successful payment, your package becomes active automatically. If payment is pending, use Refresh or check again shortly.</p></div><div><b>5. Invite referrals</b><p>Open <strong>My Referrals</strong> and copy your referral link. People who register through your link appear in your network.</p></div><div><b>6. Track earnings</b><p>Your commissions are shown under <strong>My Referrals</strong>. Package payments and account activity appear under <strong>Transactions</strong>.</p></div><div><b>7. Withdraw earnings</b><p>Open <strong>Wallet</strong>, enter at least KSh 100 and a valid M-Pesa number, then submit the request. Withdrawals are reviewed by the administrator.</p></div><div><b>8. Need help?</b><p>Use the blinking <strong>Support</strong> button to contact NEXORA support directly on WhatsApp.</p></div></div><div className="modalfoot"><a className="secondary supportinline" href="https://wa.me/254703265774" target="_blank" rel="noreferrer"><MessageCircle size={17}/> WhatsApp Support <ExternalLink size={14}/></a></div></div></div>}
function SupportButton(){return <a className="supportfloat" href="https://wa.me/254703265774" target="_blank" rel="noreferrer" aria-label="Contact NEXORA support on WhatsApp"><MessageCircle size={20}/><span>Support</span></a>}
function Auth({onLogin}){const [mode,setMode]=useState("login"),[f,setF]=useState({}),[err,setErr]=useState(""),[busy,setBusy]=useState(false),[instructions,setInstructions]=useState(false);const ref=new URLSearchParams(location.search).get("ref")||"";const submit=async e=>{e.preventDefault();setErr("");if(mode==="register"&&!validPhone(f.phone))return setErr("Enter a valid Kenyan phone number: 07…, 011…, 2547… or 2541….");setBusy(true);try{const d=await api(`/auth/${mode==="login"?"login":"register"}`,{method:"POST",body:JSON.stringify({...f,phone:mode==="register"?cleanPhone(f.phone):f.phone,referralCode:f.referralCode||ref})});localStorage.setItem("token",d.token);await onLogin()}catch(e){setErr(e.message)}finally{setBusy(false)}};return <div className="auth"><div className="authbox"><div className="brand">NEXORA<span>.</span></div><p className="muted">Connect. Grow. Earn.</p><h1>{mode==="login"?"Welcome back":"Create your account"}</h1>{err&&<div className="error">{err}</div>}<form onSubmit={submit}>{mode==="register"&&<><input required placeholder="Full name" onChange={e=>setF({...f,name:e.target.value})}/><input required inputMode="tel" maxLength="13" placeholder="Phone: 07…, 011…, 2547… or 2541…" onChange={e=>setF({...f,phone:e.target.value})}/><p className="muted small phonehint">Accepted: 07xxxxxxxx · 011xxxxxxx · 2547xxxxxxxx · 2541xxxxxxxx</p></>}<input required type="email" placeholder="Email" onChange={e=>setF({...f,email:e.target.value})}/><input required minLength="8" type="password" placeholder="Password (8+ characters)" onChange={e=>setF({...f,password:e.target.value})}/>{mode==="register"&&<input placeholder={`Referral code ${ref?"(detected)":"(optional)"}`} defaultValue={ref} onChange={e=>setF({...f,referralCode:e.target.value})}/>}<button disabled={busy} className="primary">{busy?"Please wait…":mode==="login"?"Login":"Create account"}</button></form><button className="link" onClick={()=>{setMode(mode==="login"?"register":"login");setErr("")}}>{mode==="login"?"Don't have an account? Register":"Already registered? Login"}</button><button className="instructionlink" onClick={()=>setInstructions(true)}><BookOpen size={16}/> Instructions</button></div><SupportButton/>{instructions&&<Instructions onClose={()=>setInstructions(false)}/>}</div>}


const adminApi=async(path,opts={})=>{const token=localStorage.getItem("adminToken");const r=await fetch(API+path,{...opts,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Admin request failed");return d};
function AdminLogin({onLogin}){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setErr("");setBusy(true);try{const d=await adminApi("/admin/auth/login",{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("adminToken",d.token);onLogin(d.admin)}catch(e){setErr(e.message)}finally{setBusy(false)}};return <div className="adminauth"><div className="adminloginbox"><div className="adminlogo"><img src="/nexora-logo.png"/><div><div className="brand">NEXORA<span>.</span></div><span>ADMIN CONTROL</span></div></div><div className="adminshield"><LockKeyhole size={26}/></div><h1>Administrator login</h1><p className="muted">Secure access to users, payments, withdrawals and packages.</p>{err&&<div className="error">{err}</div>}<form onSubmit={submit}><label>Email</label><input required type="email" autoComplete="username" placeholder="admin@yourdomain.com" value={email} onChange={e=>setEmail(e.target.value)}/><label>Password</label><input required type="password" autoComplete="current-password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy} className="primary adminloginbtn"><LogIn size={17}/>{busy?"Signing in…":"Sign in securely"}</button></form><a className="adminback" href="/">← Back to member login</a></div></div>}
function AdminApp(){const [admin,setAdmin]=useState(null),[loading,setLoading]=useState(true),[page,setPage]=useState("overview"),[data,setData]=useState({overview:null,users:[],transactions:[],withdrawals:[],packages:[]}),[error,setError]=useState(""),[search,setSearch]=useState(""),[mobile,setMobile]=useState(false),[notice,setNotice]=useState("");
 const load=async(show=true)=>{if(show)setLoading(true);setError("");try{const a=await adminApi("/admin/me");setAdmin(a.admin);const [overview,users,transactions,withdrawals,packages]=await Promise.all([adminApi("/admin/overview"),adminApi("/admin/users"),adminApi("/admin/transactions"),adminApi("/admin/withdrawals"),adminApi("/admin/packages")]);setData({overview,users,transactions,withdrawals,packages});}catch(e){localStorage.removeItem("adminToken");setAdmin(null);if(!String(e.message).toLowerCase().includes("session"))setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{if(localStorage.getItem("adminToken"))load();else setLoading(false)},[]);
 const action=async(fn,msg)=>{try{await fn();setNotice(msg);await load(false)}catch(e){setError(e.message)}};
 if(loading&&!admin)return <div className="loading">Loading NEXORA Admin…</div>;if(!admin)return <AdminLogin onLogin={a=>{setAdmin(a);load(false)}}/>;
 const nav=[["overview","Overview",BarChart3],["users","Users",UsersRound],["transactions","Transactions",ReceiptText],["withdrawals","Withdrawals",HandCoins],["packages","Packages",PackageIcon]];
 const logout=()=>{localStorage.removeItem("adminToken");setAdmin(null)};
 const title=nav.find(x=>x[0]===page)?.[1]||"Overview";
 return <div className="adminapp"><aside className={mobile?"open":""}><div className="adminnavbrand"><img src="/nexora-logo.png"/><div><b>NEXORA</b><small>ADMIN</small></div></div>{nav.map(([id,t,I])=><button key={id} className={page===id?"active":""} onClick={()=>{setPage(id);setMobile(false)}}><I size={18}/>{t}</button>)}<div className="adminnavspacer"/><button onClick={()=>setNotice(`Paystack is currently in ${data.overview?.paystackMode||"unknown"} mode.`)}><Settings2 size={18}/>Payment mode</button><button onClick={logout}><LogOut size={18}/>Logout</button></aside><main className="adminmain"><header className="adminheader"><button className="mobilemenu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div><b>{title}</b><div className="muted small">NEXORA administrator console</div></div><div className="adminuser"><ShieldCheck size={17}/><span>{admin.name}</span></div></header>{error&&<div className="error topmsg"><span>{error}</span><button onClick={()=>load(false)}><RefreshCw size={15}/> Retry</button></div>}{notice&&<div className="notice topmsg"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
 {page==="overview"&&<AdminOverview data={data.overview} onRefresh={()=>load(false)}/>} {page==="users"&&<AdminUsers rows={data.users} search={search} setSearch={setSearch} action={action}/>} {page==="transactions"&&<AdminTransactions rows={data.transactions}/>} {page==="withdrawals"&&<AdminWithdrawals rows={data.withdrawals} action={action}/>} {page==="packages"&&<AdminPackages rows={data.packages} action={action}/>}</main></div>}
function AdminOverview({data,onRefresh}){if(!data)return <div className="adminloading">Loading overview…</div>;const cards=[["Total users",data.users,UsersRound],["Active users",data.activeUsers,UserCheck],["Transactions",data.transactions,ReceiptText],["Pending payments",data.pendingPayments,Clock3],["Successful package sales",money(data.successfulPayments),CheckCircle2],["Pending withdrawals",data.pendingWithdrawals,HandCoins],["Total commissions",money(data.totalCommissions),ArrowUpRight],["Paystack mode",String(data.paystackMode||"unknown").toUpperCase(),ShieldCheck]];return <section className="adminsection"><div className="adminsectionhead"><div><span className="pill">CONTROL CENTER</span><h1>Good to see you, Administrator</h1><p className="muted">Monitor NEXORA activity and handle member operations from one place.</p></div><button className="secondary" onClick={onRefresh}><RefreshCw size={16}/> Refresh</button></div><div className="adminstats">{cards.map(([label,value,I])=><div className="adminstat" key={label}><I size={19}/><span>{label}</span><strong>{value}</strong></div>)}</div><div className="adminpanel"><div><h3>Admin access</h3><p className="muted">This area is protected separately from member accounts. Admin sessions expire after 12 hours.</p></div><div className="adminquick"><span><Check size={14}/> Users</span><span><Check size={14}/> Payments</span><span><Check size={14}/> Withdrawals</span><span><Check size={14}/> Packages</span></div></div><div className="adminpanel warningpanel"><div><h3>Paystack environment</h3><p className="muted">Current server key mode: <strong>{data.paystackMode}</strong>. Live mode is required for real M-Pesa transactions; keep secret keys on the server only.</p></div><a className="secondary" href="https://dashboard.paystack.com/" target="_blank" rel="noreferrer">Open Paystack</a></div></section>}
function AdminUsers({rows,search,setSearch,action}){const filtered=rows.filter(u=>!search||`${u.name} ${u.email} ${u.phone} ${u.referralCode}`.toLowerCase().includes(search.toLowerCase()));return <section className="adminsection"><div className="adminsectionhead"><div><h1>Users</h1><p className="muted">Search members, review packages and manage account status.</p></div></div><div className="adminsearch"><Search size={17}/><input placeholder="Search name, email, phone or referral code" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="adminpanel tablepanel"><div className="admintable"><div className="adminrow adminrowhead"><span>User</span><span>Phone</span><span>Package</span><span>Balance</span><span>Status</span><span>Action</span></div>{filtered.map(u=><div className="adminrow" key={u.id}><div><b>{u.name}</b><small>{u.email}</small><small>Ref: {u.referralCode}</small></div><span>{u.phone}</span><span>{u.package?.name||"—"}</span><span>{money(u.wallet?.balance)}</span><span><em className={`adminstatus ${u.status.toLowerCase()}`}>{u.status}</em></span><button className="rowaction" onClick={()=>action(()=>adminApi(`/admin/users/${u.id}/status`,{method:"PATCH",body:JSON.stringify({status:u.status==="ACTIVE"?"SUSPENDED":"ACTIVE"})}),u.status==="ACTIVE"?"User suspended":"User reactivated")}>{u.status==="ACTIVE"?<><Ban size={14}/> Suspend</>:<><UserCheck size={14}/> Activate</>}</button></div>)}{!filtered.length&&<div className="adminempty">No users match your search.</div>}</div></div></section>}
function AdminTransactions({rows}){return <section className="adminsection"><div className="adminsectionhead"><div><h1>Transactions</h1><p className="muted">Package payments, commissions, refunds and withdrawal records.</p></div></div><div className="adminpanel tablepanel"><div className="admintable"><div className="adminrow adminrowhead"><span>Reference</span><span>Member</span><span>Type</span><span>Amount</span><span>Status</span><span>Date</span></div>{rows.map(x=><div className="adminrow" key={x.id}><div><b>{x.reference}</b><small>{x.metadata?.paystack?.gateway_response||x.metadata?.paystack?.display_text||""}</small></div><div><b>{x.user?.name}</b><small>{x.user?.email}</small></div><span>{x.type.replaceAll("_"," ")}</span><strong>{money(x.amount)}</strong><em className={`adminstatus ${String(x.status).toLowerCase()}`}>{x.status}</em><small>{new Date(x.createdAt).toLocaleString()}</small></div>)}{!rows.length&&<div className="adminempty">No transactions yet.</div>}</div></div></section>}
function AdminWithdrawals({rows,action}){return <section className="adminsection"><div className="adminsectionhead"><div><h1>Withdrawals</h1><p className="muted">Review M-Pesa withdrawal requests and mark them processed.</p></div></div><div className="adminpanel tablepanel"><div className="admintable"><div className="adminrow adminrowhead"><span>Member</span><span>Phone</span><span>Amount</span><span>Reference</span><span>Status</span><span>Action</span></div>{rows.map(x=><div className="adminrow" key={x.id}><div><b>{x.user?.name}</b><small>{x.user?.email}</small></div><span>{x.phone}</span><strong>{money(x.amount)}</strong><span>{x.reference}</span><em className={`adminstatus ${String(x.status).toLowerCase()}`}>{x.status}</em><div className="rowactions">{x.status!=="PAID"&&x.status!=="FAILED"&&<><button className="rowaction" onClick={()=>action(()=>adminApi(`/admin/withdrawals/${x.id}/status`,{method:"PATCH",body:JSON.stringify({status:"PROCESSING"})}),"Withdrawal marked processing")}><Clock3 size={13}/> Process</button><button className="rowaction successaction" onClick={()=>action(()=>adminApi(`/admin/withdrawals/${x.id}/status`,{method:"PATCH",body:JSON.stringify({status:"PAID"})}),"Withdrawal marked paid")}><Check size={13}/> Paid</button><button className="rowaction dangeraction" onClick={()=>action(()=>adminApi(`/admin/withdrawals/${x.id}/status`,{method:"PATCH",body:JSON.stringify({status:"FAILED"})}),"Withdrawal failed and funds returned")}><Ban size={13}/> Fail</button></>}</div></div>)}{!rows.length&&<div className="adminempty">No withdrawal requests yet.</div>}</div></div></section>}
function AdminPackages({rows,action}){const [editing,setEditing]=useState(null),[form,setForm]=useState({});const open=p=>{setEditing(p.id);setForm({price:p.price,directCommission:p.directCommission,level2Commission:p.level2Commission,active:p.active})};return <section className="adminsection"><div className="adminsectionhead"><div><h1>Packages</h1><p className="muted">Adjust pricing, commissions and availability.</p></div></div><div className="adminpackagegrid">{rows.map(p=><div className="adminpkg" key={p.id}><div className="adminpkghead"><div><span className="pkgname">{p.name}</span><small>{p._count?.users||0} members</small></div><em className={`adminstatus ${p.active?"active":"suspended"}`}>{p.active?"ACTIVE":"OFF"}</em></div>{editing===p.id?<div className="adminedit"><label>Price<input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Direct commission<input type="number" value={form.directCommission} onChange={e=>setForm({...form,directCommission:e.target.value})}/></label><label>Level 2 commission<input type="number" value={form.level2Commission} onChange={e=>setForm({...form,level2Commission:e.target.value})}/></label><label className="checkline"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><div className="rowactions"><button className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" onClick={()=>action(()=>adminApi(`/admin/packages/${p.id}`,{method:"PATCH",body:JSON.stringify({...form,price:Number(form.price),directCommission:Number(form.directCommission),level2Commission:Number(form.level2Commission)})}),"Package updated")}>Save</button></div></div>:<><h2>{money(p.price)}</h2><div className="commission"><div><b>{money(p.directCommission)}</b><small>Direct</small></div><div><b>{money(p.level2Commission)}</b><small>Level 2</small></div></div><button className="secondary" onClick={()=>open(p)}>Edit package</button></>}</div>)}</div></section>}

function App(){
 if(window.location.pathname==="/admin" || window.location.pathname.startsWith("/admin/")) return <AdminApp/>;
 const [me,setMe]=useState(null),[page,setPage]=useState("dashboard"),[packages,setPackages]=useState([]),[referrals,setReferrals]=useState({direct:[],level2:[]}),[earnings,setEarnings]=useState([]),[transactions,setTransactions]=useState([]),[msg,setMsg]=useState(""),[error,setError]=useState(""),[mobile,setMobile]=useState(false),[loading,setLoading]=useState(true),[instructions,setInstructions]=useState(false),[phoneModal,setPhoneModal]=useState(null),[payment,setPayment]=useState(null);
 const load=async(showSpinner=true)=>{if(showSpinner)setLoading(true);setError("");try{const m=await api("/me");setMe(m);const results=await Promise.allSettled([api("/packages"),api("/referrals"),api("/earnings"),api("/transactions")]);if(results[0].status==="fulfilled")setPackages(results[0].value);if(results[1].status==="fulfilled")setReferrals(results[1].value);if(results[2].status==="fulfilled")setEarnings(results[2].value);if(results[3].status==="fulfilled")setTransactions(results[3].value);const failed=results.find(x=>x.status==="rejected");if(failed)setError(failed.reason?.message||"Some account data could not be loaded");}catch(e){if(e.message.toLowerCase().includes("session")||e.message.toLowerCase().includes("authentication")||e.message.toLowerCase().includes("expired")){localStorage.removeItem("token");setMe(null)}else setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{if(localStorage.getItem("token"))load();else setLoading(false)},[]);
 if(loading&&!me)return <div className="loading">Loading NEXORA…</div>;if(!me)return <Auth onLogin={()=>load()}/>;
 const nav=[["dashboard","Dashboard",LayoutDashboard],["packages","Packages",PackageIcon],["referrals","My Referrals",Users],["wallet","Wallet",WalletCards],["transactions","Transactions",History]];
 const startPayment=async(phone,p)=>{
  setPhoneModal(null);
  setMsg("");setError("");
  try{
    const normalized=cleanPhone(phone);
    if(!validPhone(normalized))return setError("Invalid Kenyan phone number. Use 07…, 011…, 2547… or 2541….");
    const d=await api("/payments/initialize",{method:"POST",body:JSON.stringify({packageId:p.id,phone:normalized})});
    const initialStatus=d.status||"pending";
    setPayment({reference:d.reference,package:p,phone:normalized,status:initialStatus,display_text:d.display_text||"",message:d.message&&d.message!=="Charge attempted"?d.message:""});
    if(initialStatus==="success"){
      await load(false);
      setMsg("Payment confirmed. Your package is now active.");
      return;
    }
    if(initialStatus==="failed")return;
    let tries=0;
    const poll=async()=>{
      if(tries>=12)return;
      tries++;
      try{
        const v=await api(`/payments/status/${d.reference}`);
        setPayment(x=>x?{...x,status:v.status||"pending",display_text:v.display_text||x.display_text,message:v.message&&v.message!=="Charge attempted"?v.message:x.message}:x);
        if(v.status==="success"){
          await load(false);
          setMsg("Payment confirmed. Your package is now active.");
          return;
        }
        if(v.status==="failed")return;
      }catch{}
      if(tries<12)setTimeout(poll,10000);
    };
    setTimeout(poll,10000);
  }catch(e){setError(e.message)}
 };
 const purchase=async p=>{
  setMsg("");setError("");
  if(!p?.id)return;
  setPhoneModal({package:p,phone:cleanPhone(me.user.phone||"")});
 };
 const copy=async()=>{const link=`${location.origin}/?ref=${me.user.referralCode}`;try{await navigator.clipboard.writeText(link);setMsg("Referral link copied.")}catch{window.prompt("Copy your referral link:",link)}};
 const logout=()=>{localStorage.removeItem("token");setMe(null);setPage("dashboard")};
 return <div className="app"><aside className={mobile?"open":""}><div className="brand">NEXORA<span>.</span></div>{nav.map(([id,t,I])=><button className={page===id?"active":""} onClick={()=>{setPage(id);setMobile(false);setMsg("")}} key={id}><I size={19}/>{t}</button>)}<button onClick={()=>setInstructions(true)}><BookOpen size={19}/>Instructions</button><button onClick={logout}><LogOut size={19}/>Logout</button></aside><main><header><button className="mobilemenu" onClick={()=>setMobile(!mobile)} aria-label="Open menu">{mobile?<X/>:<Menu/>}</button><div><b>{nav.find(x=>x[0]===page)?.[1]||"Dashboard"}</b><div className="muted small">Manage your NEXORA account</div></div><div className="avatar">{me.user.name?.[0]?.toUpperCase()||"N"}</div></header>{error&&<div className="error topmsg"><span>{error}</span><button onClick={()=>load(false)}><RefreshCw size={15}/> Retry</button></div>}{msg&&<div className="notice topmsg">{msg}</div>}{page==="dashboard"&&<Dashboard me={me} copy={copy} goPackages={()=>setPage("packages")}/>} {page==="packages"&&<Packages packages={packages} current={me.package} purchase={purchase} reload={()=>load(false)}/>} {page==="referrals"&&<Referrals data={referrals} earnings={earnings}/>} {page==="wallet"&&<Wallet me={me} load={()=>load(false)}/>} {page==="transactions"&&<Transactions rows={transactions} onOpenPending={x=>{const packageId=x.metadata?.packageId;const pkg=packages.find(p=>p.id===packageId);if(pkg){setPayment({reference:x.reference,package:pkg,phone:cleanPhone(x.metadata?.phone||me.user.phone||""),status:String(x.status||"PENDING").toLowerCase(),display_text:x.metadata?.paystack?.display_text||"",message:""})}}}/>}</main><SupportButton/>{instructions&&<Instructions onClose={()=>setInstructions(false)}/>} {phoneModal&&<PhoneModal data={phoneModal} onCancel={()=>setPhoneModal(null)} onContinue={phone=>startPayment(phone,phoneModal.package)}/>} {payment&&<PaymentModal payment={payment} onClose={()=>setPayment(null)} onCheck={async()=>{try{const v=await api(`/payments/status/${payment.reference}`);setPayment(x=>x?{...x,status:v.status||"pending",display_text:v.display_text||x.display_text,message:v.message&&v.message!=="Charge attempted"?v.message:x.message}:x);if(v.status==="success"){await load(false);setMsg("Payment confirmed. Your package is now active.")}}catch(e){setError(e.message)}}}/>}</div>}
function PhoneModal({data,onCancel,onContinue}){
 const [phone,setPhone]=useState(data.phone||"");
 const [err,setErr]=useState("");
 const submit=e=>{e.preventDefault();setErr("");if(!validPhone(phone))return setErr("Use 07…, 011…, 2547… or 2541….");onContinue(phone)};
 return <div className="modalbackdrop" onClick={onCancel}><div className="modal phonemodal" onClick={e=>e.stopPropagation()}><div className="modalhead"><div><span className="pill">M-PESA PAYMENT</span><h2>Enter your M-Pesa number</h2></div><button className="iconbtn" onClick={onCancel}><X size={20}/></button></div><form onSubmit={submit}><div className="paymentbody phonebody"><div className="phonepackage"><div><span>Package</span><strong>{data.package?.name}</strong></div><div><span>Amount</span><strong>{money(data.package?.price)}</strong></div></div><label className="fieldlabel">M-Pesa phone number</label><input autoFocus inputMode="tel" maxLength="13" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="07…, 011…, 2547… or 2541…"/><p className="muted small">We'll send the payment request to this number. You will approve it with your M-Pesa PIN.</p>{err&&<div className="error">{err}</div>}</div><div className="modalfoot paymentfoot"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button type="submit" className="primary"><MessageCircle size={16}/> Send M-Pesa request</button></div></form></div></div>}

function PaymentModal({payment,onClose,onCheck}){
 const status=payment.status||"pending";
 const isSuccess=status==="success";
 const isFailed=status==="failed";
 const isPending=!isSuccess&&!isFailed;
 const title=isSuccess?"Payment successful":isFailed?"Payment failed":"M-Pesa request sent";
 const text=isSuccess?"Your package has been activated.":isFailed?"The M-Pesa payment was not completed. You can close this window and try again.":"Check your phone now. An M-Pesa prompt should be waiting for your approval.";
 return <div className="modalbackdrop" onClick={onClose}><div className="modal paymentmodal" onClick={e=>e.stopPropagation()}><div className="modalhead"><div><span className={`pill ${isSuccess?"payment-success":isFailed?"payment-failed":"payment-pending"}`}>{isSuccess?"COMPLETED":isFailed?"FAILED":"WAITING FOR PAYMENT"}</span><h2>{title}</h2></div><button className="iconbtn" onClick={onClose}><X size={20}/></button></div><div className="paymentbody"><div className="paymentstatus"><div className={`paymenticon ${isSuccess?"success":isFailed?"failed":"pending"}`}>{isSuccess?<CheckCircle2 size={28}/>:isFailed?<X size={28}/>:<RefreshCw size={28}/>}</div><div><b>{text}</b><p className="muted">{isSuccess?"Payment confirmed by NEXORA.":isFailed?(payment.display_text||"Please try the payment again."):(payment.display_text||"Please enter your M-Pesa PIN on your phone to approve the payment.")}</p></div></div><div className="paymentdetails"><div><span>Package</span><strong>{payment.package?.name}</strong></div><div><span>Amount</span><strong>{money(payment.package?.price)}</strong></div><div><span>M-Pesa number</span><strong>{payment.phone}</strong></div><div><span>Reference</span><strong>{payment.reference}</strong></div></div>{isPending&&<div className="paymentwait"><div className="paymentwaittitle"><span className="live-dot"></span><strong>Waiting for confirmation</strong></div><p className="muted small">We will keep checking automatically. Paystack recommends waiting at least 10 seconds before checking a pending charge.</p></div>}{payment.message&&<p className="muted small">{payment.message}</p>}</div><div className="modalfoot paymentfoot">{isPending&&<button className="secondary" onClick={onCheck}><RefreshCw size={16}/> Check payment status</button>}<button className="primary paymentclose" onClick={onClose}>{isSuccess?"Go to dashboard":isFailed?"Close":"Close for now"}</button></div></div></div>}

function Dashboard({me,copy,goPackages}){return <><section className="hero"><div><span className="pill">MEMBER DASHBOARD</span><h1>Hello, {me.user.name.split(" ")[0]} 👋</h1><p>Here's what's happening with your account.</p></div><div className="heroicon"><ShieldCheck size={38}/></div></section><div className="cards"><Card title="Available balance" value={money(me.wallet?.balance)}/><Card title="Total earned" value={money(me.wallet?.totalEarned)}/><Card title="Direct referrals" value={me.stats.direct}/><Card title="Level 2 network" value={me.stats.level2}/></div><div className="grid2"><div className="panel"><h3>Your package</h3>{me.package?<div className="packageactive"><div><b>{me.package.name}</b><span>{money(me.package.price)}</span></div><div><small>Direct</small><strong>{money(me.package.directCommission)}</strong></div><div><small>Level 2</small><strong>{money(me.package.level2Commission)}</strong></div></div>:<><p className="muted">No active package. Choose a package to get started.</p><button className="primary narrow" onClick={goPackages}>View packages</button></>}</div><div className="panel"><h3>Your referral link</h3><div className="copybox"><span>{location.origin}/?ref={me.user.referralCode}</span><button onClick={copy}><Copy size={17}/> Copy</button></div><p className="muted small">Share this link to invite people to NEXORA.</p></div></div></>}
function Card({title,value}){return <div className="stat"><span>{title}</span><strong>{value}</strong><ArrowUpRight size={18}/></div>}
function Packages({packages,current,purchase,reload}){return <section><div className="sectionhead"><div><h1>Choose your package</h1><p className="muted">Select the membership package that fits your goals.</p></div><button className="secondary" onClick={reload}><RefreshCw size={16}/> Refresh</button></div>{packages.length?<div className="packages">{packages.map((p,i)=><div className={`pkg ${i===2?"featured":""}`} key={p.id}>{i===2&&<div className="popular">POPULAR</div>}<span className="pkgname">{p.name}</span><h2>{money(p.price)}</h2><div className="commission"><div><b>{money(p.directCommission)}</b><small>Direct referral</small></div><div><b>{money(p.level2Commission)}</b><small>Level 2 referral</small></div></div><button className="primary" disabled={current?.id===p.id} onClick={()=>purchase(p)}>{current?.id===p.id?<><CheckCircle2 size={16}/> Current package</>:"Purchase package"}</button></div>)}</div>:<div className="panel empty"><PackageIcon size={32}/><h3>No packages available</h3><p className="muted">We couldn't load the package list.</p><button className="primary narrow" onClick={reload}>Reload packages</button></div>}</section>}
function Referrals({data,earnings}){return <><div className="cards three"><Card title="Direct referrals" value={data.direct.length}/><Card title="Level 2 referrals" value={data.level2.length}/><Card title="Commission records" value={earnings.length}/></div><div className="panel"><h3>Direct referrals</h3><div className="table">{data.direct.map(x=><div className="row" key={x.id}><div><b>{x.name}</b><small>{x.email}</small></div><span>{x.package?.name||"No package"}</span><span>{new Date(x.createdAt).toLocaleDateString()}</span></div>)}{!data.direct.length&&<p className="muted">No direct referrals yet.</p>}</div></div><div className="panel"><h3>Level 2 referrals</h3>{data.level2.length?data.level2.map(x=><div className="row simple" key={x.id}><div><b>{x.name}</b><small>{x.email}</small></div><span>{x.package?.name||"No package"}</span></div>):<p className="muted">No Level 2 referrals yet.</p>}</div><div className="panel"><h3>Recent commissions</h3>{earnings.length?earnings.map(x=><div className="row simple" key={x.id}><div><b>{x.level===1?"Direct":"Level 2"} referral</b><small>{x.sourceUser.name}</small></div><strong className="green">+{money(x.amount)}</strong></div>):<p className="muted">No commissions yet.</p>}</div></>}
function Wallet({me,load}){const [amount,setAmount]=useState(""),[phone,setPhone]=useState(me.user.phone||""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);const withdraw=async()=>{setMsg("");const n=Number(amount);if(!Number.isInteger(n)||n<100)return setMsg("Enter a whole amount of at least KSh 100.");if(n>Number(me.wallet?.balance||0))return setMsg("The withdrawal amount exceeds your available balance.");if(!validPhone(phone))return setMsg("Enter a valid Kenyan phone number: 07…, 011…, 2547… or 2541…. ");setBusy(true);try{const d=await api("/withdrawals",{method:"POST",body:JSON.stringify({amount:n,phone:cleanPhone(phone)})});setMsg(`${d.message}. Reference: ${d.reference}`);setAmount("");await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}};return <><div className="walletbig"><span>Available balance</span><strong>{money(me.wallet?.balance)}</strong><p>Total earned {money(me.wallet?.totalEarned)} · Pending {money(me.wallet?.pendingBalance)} · Withdrawn {money(me.wallet?.totalWithdrawn)}</p></div><div className="panel formpanel"><h3>Request withdrawal</h3>{msg&&<div className="notice">{msg}</div>}<input type="number" min="100" step="1" placeholder="Amount (KSh)" value={amount} onChange={e=>setAmount(e.target.value)}/><input inputMode="tel" maxLength="13" placeholder="M-Pesa phone: 07…, 011…, 2547… or 2541…" value={phone} onChange={e=>setPhone(e.target.value)}/><p className="muted small phonehint">Accepted: 07xxxxxxxx · 011xxxxxxx · 2547xxxxxxxx · 2541xxxxxxxx</p><button disabled={busy} className="primary" onClick={withdraw}>{busy?"Submitting…":"Request withdrawal"}</button><p className="muted small">Minimum withdrawal: KSh 100. Withdrawals are reviewed/processed by the administrator.</p></div></>}
function Transactions({rows,onOpenPending}){return <section><div className="sectionhead"><div><h1>Transactions</h1><p className="muted">Your recent account activity.</p></div></div><div className="panel">{rows.length?rows.map(x=><div className="row simple" key={x.id}><div><b>{x.type.replaceAll("_"," ")}</b><small>{new Date(x.createdAt).toLocaleString()} · {x.reference}</small></div><div className="transactionright"><strong>{money(x.amount)}</strong><small className={`txstatus ${String(x.status||"").toLowerCase()}`}>{x.status}</small>{String(x.status||"").toUpperCase()==="PENDING"&&x.type==="PACKAGE_PURCHASE"&&<button className="txcheck" onClick={()=>onOpenPending(x)}><RefreshCw size={13}/> Check payment</button>}</div></div>):<p className="muted">No transactions yet.</p>}</div></section>}
createRoot(document.getElementById("root")).render(<App/>);
